# Generated by Django 5.1.1 on 2024-11-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='videolecture',
            name='description',
            field=models.TextField(default='No description available'),
        ),
    ]
